### ISSUE TITLE
Integrate new paper number background images and implement handles

### ISSUE THREAD

**Issue by chrisklus** [phetsims/counting-common#1]
Todo for this issue:

- [x] swap out the old paper number images for new ones
- [x] position the text correctly on each background image
- [x] draw the lollipop handles (solid if the handle will move a stack off another, targeted if the handle will peel away some of the value from a stack)
- [x] move the touch areas to the appropriate positions on the paper numbers

**Comment by chrisklus** [comment]
A first draft of this issue is complete. Still to do:

- [ ] respond to feedback from designers and teachers and make checklist items accordingly
- [ ] code cleanup (marked with many TODOs in code)

**Comment by chrisklus** [comment]
Closing this is issue. The remaining work for for cleaning up the paper numbers and play objects has been moved to https://github.com/phetsims/number-play/issues/117 (since they are more similar to each other now). I'll leave the other checkbox from https://github.com/phetsims/counting-common/issues/1#issuecomment-906590247 for amanda to make a separate issue for during interviews.

**Comment by samreid** [comment]
As discovered in https://github.com/phetsims/chipper/issues/946, there are TODOs in the code referring to this issue.  Reopening.

**Comment by chrisklus** [comment]
Thanks @samreid. The remaining TODO for this issue was moved to a new issue in MAT, see https://github.com/phetsims/make-a-ten/issues/306. Closing
