### ISSUE TITLE
Confusing split behavior

### ISSUE THREAD

**Issue by chrisklus** [phetsims/counting-common#14]
@pixelzoom and @marlitas noted that when splitting a paper number with the handle, it's confusing that you don't see that the one is separated until you actually drag it away and it reveals the paper number it came from behind it. Also, it's weird that when grabbing a one off of another paper number, you are dragging it while having your mouse/finger over open space since the handle disappears, which @pixelzoom noted made him feel like he should let go since he didn't know what he was holding on to.

We were thinking it would be nice if the one snaps up and to the left or right a little bit, such that your cursor is now grabbing the top of the paper.

**Comment by amanda-phet** [comment]
I think it would be fine for the one to jump up a little. I would like to try just jumping up (y-offset) before also including an x-offset.

**Comment by marlitas** [comment]
This functionality was added in the above commits. Over to @chrisklus for review.

**Comment by chrisklus** [comment]
@marlitas and I reviewed together and found a simpler way to get the same behavior, committed above.

Passing over to @amanda-phet for design review. Note that the "jump" is not a consistent distance for all splits, the new card just jumps such that the user is holding the top of the new card. I think this feels nice but wanted to point out the difference.

**Comment by amanda-phet** [comment]
I like this change!
