### ISSUE TITLE
Make "1" appear less like a tally mark

### ISSUE THREAD

**Issue by chrisklus** [phetsims/counting-common#8]
As discussed in design meeting today - we got feedback that the ones look too much like a tally mark. @amanda-phet could you try out adding a little part at the top to make it look a little bit more like a digital 1? We also might want to try adding a base to the 1, but I'm not sure if that's needed.

**Comment by amanda-phet** [comment]
I'm going to mock up three options and see how I like them when there are twenty visible at a time 

1. A notch at the top that's not quite as big as a serif
2. A more exaggerated serif at the top
3. An exaggerated serif plus a little base at the bottom of the one

**Comment by amanda-phet** [comment]
We liked this version the best: 

![image](https://user-images.githubusercontent.com/7852916/161144315-007aadd5-bc40-4904-934c-aa9f4200314b.png)


I will deliver the png to @chrisklus and we will fine-tune the placement on the paper.

**Comment by amanda-phet** [comment]
@chrisklus and I just need to adjust the placement of the one on the paper now that it is wider.

**Comment by chrisklus** [comment]
@amanda-phet and I met and moved the 1 over a little to the right to make the 10 look better. Closing.
